### ISSUE TITLE
ERROR: Can not login to Directus

### ISSUE THREAD

**Issue by ghost** [peXed/gridsome-source-directus#10]
I get the following error with a directus instance I spun up and double and triple checked the URL and login info for:

`DIRECTUS ERROR: Can not login to Directus {
  code: 3,
  message: 'Unauthorized request',
  class: 'Directus\\Exception\\UnauthorizedException',
  file: '/app/code/src/helpers/app.php',
  line: 287
}`

Is anyone else encountering this issue? To specify, I did make the collection I am attempting to fetch and have done no other configuration. Is there something else I need to be doing on the directus side of things?

**Comment by peXed** [comment]
Hello @AtriLahiji and sorry for the delay.

Did you setup an own account for the Plugin to fetch the data? Did you set it up in the plugins config of Gridsome, like described in the readme?
