### ISSUE TITLE
How to deal with files when specified as O2M ?

### ISSUE THREAD

**Issue by denisbertrandbe** [peXed/gridsome-source-directus#4]
Hello @peXed ,

In directus, I have a collection with a "multiple files" field (O2M).

But on the gridsome side, I can't create a query to get files details. I only have details from the junction table.

What's the best way to have all details of linked files ?

**Comment by peXed** [comment]
Hello @justdoweb-be !

You can create a query to get all files. I do it on multiple projects (e.g. for gallerys).

You should get all fields with `fields: '*.*.*'`.

In the readme, you will find a full example.

Additionally, you can now use: `downloadImages: true` or `downloadFiles: true` to let the plugin download the images/files!

If this is not solving your issue. How did you setup the O2M?

**Comment by denisbertrandbe** [comment]
Oh, nice ! It works very well with ```'*.*.*'```

Perfect, thank you.
