### ISSUE TITLE
gridsome_image is always null

### ISSUE THREAD

**Issue by JasonKoopmans** [peXed/gridsome-source-directus#5]
I've installed the 1.1 version of the plugin and though many things are working well, the gridsome_image field is always null when queried.  The files are downloaded in the `.cache-directus` folder.   Many of the other directus-fed fields are present. 

Directus version: 8.6.2

```
collections: [
          {
            name: 'rotator',
            status: 'published',
            fields: '*.*.*',
            downloadImages: true,
            downloadFiles: true,
          }
```

What else can I share to help diagnose this?

**Comment by peXed** [comment]
Hello @JasonKoopmans  sorry for the delay. Was stuck in projects.

The gridsome_image should not be null, but an GridsomeImage field. What datatype is the source field in directus?

**Comment by JasonKoopmans** [comment]
All good @pexed,

Its a file in Directus.  Should it be something else?

EDIT: I pulled this up again and looked in the graphql and the gridsome_image is populated now, and when building, the dist folder contains the assets I was missing before.  Not sure what contributed to the change in my results, but this can be closed.
