### ISSUE TITLE
Filtering the collection using the Directus filter option

### ISSUE THREAD

**Issue by JasonKoopmans** [peXed/gridsome-source-directus#6]
I'd like to use filtering in directus using published_on and expired_on fields to control what content gets build into the site.  In the docs, it's suggested that other parameters can be passed to the directus api.  Is filter on of them. I've been trying some different options and can't seem to get it to work.  

```
collections: [
          {
            name: 'rotator',
            status: 'published',
            fields: '*.*.*',
            downloadImages: true,
            downloadFiles: true,
            //filter: "[published_on][lte]=now"
          }, 
```

**Comment by peXed** [comment]
You can use the filter, but you have to use it like mentioned in the JS SDK:

`filter: {
    runtime: {
      gt: 200
    }`

https://docs.directus.io/guides/js-sdk.html#reference
